export const CONFIG = {
  startingHp: 20,
  handSize: 5,
  forgeWindowSize: 7,
  mergeTotals: [7, 8, 9],
  tier2FuelCost: 1,          // default; per-variant override in elements.ts wins
  tier3FuelCost: 2,
  hailMaryBurn: 3,
  hailMaryDamage: 1,
  enemyPower: { tower: 2, stronghold: 4, fortress: 6 } as Record<string, number>,
  corruptionInjection: { tower: 1, stronghold: 2, fortress: 2, manifestation: 4 } as Record<string, number>,
  deathCounterThreshold: 6,
  manifestationClock: 10,
  startingCorruption: 1,
  rewardPoints: { tower: 1, stronghold: 2, fortress: 3, manifestation: 5 } as Record<string, number>,
  relicCost: 4,
  reducedStrugglesCost: 6,
  healAmount: 4,
  scoutBaseCost: 1,
  windowWidenAmount: 2,
  strugglesByRank: { tower: 0, stronghold: 1, fortress: 2, manifestation: 3 } as Record<string, number>,
  fuelMatching: 'strict' as 'strict' | 'any' | 'bonus',
  dustDeflectTable: [0, 2, 3, 5, 6],
  volcanoEruptThreshold: 2,
} as const;
